[package]
name = "rust-image"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.93"
image = "0.23.14"
kamadak-exif = "0.5.5"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "s"